In [1]:
!pip install faker

Collecting faker
  Downloading faker-40.36.0-py3-none-any.whl.metadata (16 kB)
Downloading faker-40.36.0-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 40.0 MB/s eta 0:00:00
Installing collected packages: faker
Successfully installed faker-40.36.0

In [2]:
import pandas as pd
import sqlite3
import json
import random
import logging
from faker import Faker
from datetime import datetime

In [3]:
fake = Faker()

In [4]:
print("Name:", fake.name())
print("Email:", fake.email())
print("City:", fake.city())
print("Phone:", fake.phone_number())

Name: Tony Ryan
Email: kjenkins@example.net
City: Port Jeffreychester
Phone: 247.488.6260x2962

In [5]:
customers = []

In [6]:
for i in range(100):
    customers.append({
        "customer_id": i + 1,
        "name": fake.name(),
        "email": fake.email(),
        "phone": fake.phone_number(),
        "city": fake.city(),
        "state": fake.state(),
        "country": fake.country(),
        "age": random.randint(18, 60),
        "registration_date": fake.date_between(start_date='-2y', end_date='today')
    })

In [7]:
df_customers = pd.DataFrame(customers)

In [8]:
df_customers.head()

,customer_id,name,email,phone,city,state,country,age,registration_date
0,1,Robin Hall,christopher15@example.net,712.281.6976x983,Cunninghamfort,Arkansas,Honduras,40,2026-05-21
1,2,Raymond Harrington,kevinwilson@example.com,468-792-9134,Ramseyshire,Montana,Guernsey,45,2026-01-10
2,3,Terry Mcbride,kristy37@example.net,001-847-782-6754x5413,Robertville,Vermont,Rwanda,47,2025-01-24
3,4,Marcus Hubbard,matthewblack@example.org,+1-575-450-6676x0852,Smithberg,Michigan,Lao People's Democratic Republic,40,2025-11-07
4,5,Frederick Graham,brandy52@example.com,209-843-8804,Calhounfort,Michigan,North Macedonia,37,2025-08-17

In [9]:
df_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        100 non-null    int64
 1   name               100 non-null    object
 2   email              100 non-null    object
 3   phone              100 non-null    object
 4   city               100 non-null    object
 5   state              100 non-null    object
 6   country            100 non-null    object
 7   age                100 non-null    int64
 8   registration_date  100 non-null    object
dtypes: int64(2), object(7)
memory usage: 7.2+ KB

In [10]:
df_customers.describe(include="all")

,customer_id,name,email,phone,city,state,country,age,registration_date
count,100.000000,100,100,100,100,100,100,100.000000,100
unique,NaN,100,100,100,97,46,85,NaN,95
top,NaN,Robin Hall,christopher15@example.net,712.281.6976x983,Jameston,South Dakota,Western Sahara,NaN,2026-06-27
freq,NaN,1,1,1,2,7,3,NaN,2
mean,50.500000,NaN,NaN,NaN,NaN,NaN,NaN,40.490000,NaN
std,29.011492,NaN,NaN,NaN,NaN,NaN,NaN,11.897283,NaN
min,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,18.000000,NaN
25%,25.750000,NaN,NaN,NaN,NaN,NaN,NaN,31.000000,NaN
50%,50.500000,NaN,NaN,NaN,NaN,NaN,NaN,41.000000,NaN
75%,75.250000,NaN,NaN,NaN,NaN,NaN,NaN,50.000000,NaN
max,100.000000,NaN,NaN,NaN,NaN,NaN,NaN,60.000000,NaN

In [11]:
df_customers.isnull().sum()

customer_id          0
name                 0
email                0
phone                0
city                 0
state                0
country              0
age                  0
registration_date    0
dtype: int64

In [12]:
df_customers.duplicated().sum()

np.int64(0)

In [13]:
df_customers.to_csv("customer_data.csv", index=False)

In [14]:
df_dirty = df_customers.copy()

In [15]:
# Missing primary key
df_dirty.loc[5, "customer_id"] = None

# Missing email
df_dirty.loc[10, "email"] = None

# Invalid email format
df_dirty.loc[15, "email"] = "john.gmail.com"

# Invalid phone number
df_dirty.loc[20, "phone"] = "ABCDE12345"

# Duplicate record
df_dirty = pd.concat([df_dirty, df_dirty.iloc[[25]]], ignore_index=True)

df_dirty.head(30)

,customer_id,name,email,phone,city,state,country,age,registration_date
0,1.0,Robin Hall,christopher15@example.net,712.281.6976x983,Cunninghamfort,Arkansas,Honduras,40,2026-05-21
1,2.0,Raymond Harrington,kevinwilson@example.com,468-792-9134,Ramseyshire,Montana,Guernsey,45,2026-01-10
2,3.0,Terry Mcbride,kristy37@example.net,001-847-782-6754x5413,Robertville,Vermont,Rwanda,47,2025-01-24
3,4.0,Marcus Hubbard,matthewblack@example.org,+1-575-450-6676x0852,Smithberg,Michigan,Lao People's Democratic Republic,40,2025-11-07
4,5.0,Frederick Graham,brandy52@example.com,209-843-8804,Calhounfort,Michigan,North Macedonia,37,2025-08-17
5,NaN,Catherine Randall,johnstonjustin@example.net,+1-391-440-0278x6931,Stacyfurt,Montana,Turks and Caicos Islands,42,2026-07-19
6,7.0,Laurie Hale,denisesantos@example.com,(936)307-3715,West Laurafort,Vermont,Singapore,29,2025-08-24
7,8.0,Zachary Carey,heathernoble@example.net,+1-756-433-2886x6262,North Gina,New Mexico,American Samoa,42,2026-03-01
8,9.0,Anthony Hansen,michaelperry@example.org,(794)470-7033,East Jasonhaven,New York,Andorra,22,2025-03-11
9,10.0,Tara Cannon MD,george62@example.net,637-342-2934x14950,South Michaelstad,Alabama,Lebanon,58,2024-12-27
10,11.0,Jessica Herrera,None,+1-751-856-8107x511,Victoriaport,Idaho,Western Sahara,44,2026-06-27
11,12.0,Jessica Thomas,johnprice@example.net,289-911-4122,Rodriguezfurt,Ohio,Canada,46,2025-07-01
12,13.0,Ryan Hill,ahamilton@example.net,948.945.0472,Katelynfort,Florida,Iceland,30,2024-11-10
13,14.0,Donald Martinez,stacey80@example.org,7135073727,Jameston,Oklahoma,Germany,38,2026-06-15
14,15.0,Makayla Galvan,sullivanchristopher@example.org,(484)233-1848x75714,Fullerview,Nevada,Tonga,35,2026-05-30
15,16.0,Debra Lee,john.gmail.com,306.503.9289,Sheriland,California,Argentina,56,2026-07-16
16,17.0,Michael Reed,ssmith@example.com,001-668-805-3251x44727,North Christopher,Massachusetts,Costa Rica,40,2026-06-25
17,18.0,Sean Fowler,lesliebaldwin@example.com,6433811329,Coreyfurt,North Dakota,Senegal,49,2024-12-30
18,19.0,Corey Davis,garciamatthew@example.com,6989596278,Deleonview,Illinois,Saint Lucia,26,2025-12-21
19,20.0,David Mason,shirley80@example.com,712.588.4512x103,Milesport,South Carolina,Mauritania,46,2025-03-20
20,21.0,John Lopez,harveycarrie@example.org,ABCDE12345,South Rachel,Tennessee,Poland,42,2025-05-04
21,22.0,John Lucero,allenwilliam@example.net,(978)344-7067x48623,Traciemouth,Iowa,Faroe Islands,27,2026-06-10
22,23.0,Sheri Ross,wilkinsbarbara@example.net,001-854-647-7398x695,Anitaborough,South Dakota,Pitcairn Islands,36,2024-08-15
23,24.0,Mark Dickson,colejoseph@example.net,001-545-628-4247,Michaelbury,Louisiana,Bahrain,26,2024-10-11
24,25.0,Michelle Peck,timothy14@example.com,333.327.6845x7588,Port Stephaniehaven,Alabama,Iraq,55,2024-12-04
25,26.0,Amanda Daniels,dhill@example.com,001-641-377-3406x3684,Port Kimberly,West Virginia,Western Sahara,18,2025-03-30
26,27.0,Daniel Atkins,robertsalazar@example.com,576-766-6946x96751,Port Matthewland,Rhode Island,Sri Lanka,45,2024-10-15
27,28.0,Stacie Cunningham,zcrawford@example.net,824.666.0217x86237,East Wendyport,Georgia,Nigeria,37,2025-06-30
28,29.0,Jessica Giles,mcintyrebridget@example.com,+1-919-606-4315x454,West Susan,New Jersey,United Arab Emirates,22,2025-12-23
29,30.0,Matthew Hill,hughescarol@example.net,001-911-203-7900,Billyhaven,Maine,Bulgaria,51,2026-04-09

In [16]:
df_dirty.isnull().sum()

customer_id          1
name                 0
email                1
phone                0
city                 0
state                0
country              0
age                  0
registration_date    0
dtype: int64

In [17]:
df_dirty.duplicated().sum()

np.int64(1)

In [18]:
df_dirty.loc[[5, 10, 15, 20, 100]]

,customer_id,name,email,phone,city,state,country,age,registration_date
5,NaN,Catherine Randall,johnstonjustin@example.net,+1-391-440-0278x6931,Stacyfurt,Montana,Turks and Caicos Islands,42,2026-07-19
10,11.0,Jessica Herrera,None,+1-751-856-8107x511,Victoriaport,Idaho,Western Sahara,44,2026-06-27
15,16.0,Debra Lee,john.gmail.com,306.503.9289,Sheriland,California,Argentina,56,2026-07-16
20,21.0,John Lopez,harveycarrie@example.org,ABCDE12345,South Rachel,Tennessee,Poland,42,2025-05-04
100,26.0,Amanda Daniels,dhill@example.com,001-641-377-3406x3684,Port Kimberly,West Virginia,Western Sahara,18,2025-03-30

In [19]:
missing_id = df_dirty[df_dirty["customer_id"].isnull()]

print("Missing Primary Keys:")
missing_id

Missing Primary Keys:

,customer_id,name,email,phone,city,state,country,age,registration_date
5,NaN,Catherine Randall,johnstonjustin@example.net,+1-391-440-0278x6931,Stacyfurt,Montana,Turks and Caicos Islands,42,2026-07-19

In [20]:
missing_email = df_dirty[df_dirty["email"].isnull()]

print("Missing Emails:")
missing_email

Missing Emails:

,customer_id,name,email,phone,city,state,country,age,registration_date
10,11.0,Jessica Herrera,None,+1-751-856-8107x511,Victoriaport,Idaho,Western Sahara,44,2026-06-27

In [21]:
invalid_email = df_dirty[
    ~df_dirty["email"].fillna("").str.contains("@")
]

print("Invalid Email Addresses:")
invalid_email

Invalid Email Addresses:

,customer_id,name,email,phone,city,state,country,age,registration_date
10,11.0,Jessica Herrera,None,+1-751-856-8107x511,Victoriaport,Idaho,Western Sahara,44,2026-06-27
15,16.0,Debra Lee,john.gmail.com,306.503.9289,Sheriland,California,Argentina,56,2026-07-16

In [25]:
invalid_phone = df_dirty[
    df_dirty["phone"].str.match(r"^[A-Za-z]", na=False)
]

print("Invalid Phone Numbers:")
invalid_phone

Invalid Phone Numbers:

,customer_id,name,email,phone,city,state,country,age,registration_date
20,21.0,John Lopez,harveycarrie@example.org,ABCDE12345,South Rachel,Tennessee,Poland,42,2025-05-04

In [26]:
duplicates = df_dirty[df_dirty.duplicated()]

print("Duplicate Records:")
duplicates

Duplicate Records:

,customer_id,name,email,phone,city,state,country,age,registration_date
100,26.0,Amanda Daniels,dhill@example.com,001-641-377-3406x3684,Port Kimberly,West Virginia,Western Sahara,18,2025-03-30

In [27]:
print("========== DATA QUALITY REPORT ==========")

print(f"Total Records          : {len(df_dirty)}")
print(f"Missing Customer IDs   : {missing_id.shape[0]}")
print(f"Missing Emails         : {missing_email.shape[0]}")
print(f"Invalid Emails         : {invalid_email.shape[0]}")
print(f"Invalid Phone Numbers  : {invalid_phone.shape[0]}")
print(f"Duplicate Records      : {duplicates.shape[0]}")

========== DATA QUALITY REPORT ==========
Total Records          : 101
Missing Customer IDs   : 1
Missing Emails         : 1
Invalid Emails         : 2
Invalid Phone Numbers  : 1
Duplicate Records      : 1

In [28]:
transactions = []

for i in range(50):
    transaction = {
        "transaction_id": i + 1,
        "customer": {
            "customer_id": random.randint(1, 100),
            "name": fake.name()
        },
        "payment": {
            "amount": round(random.uniform(100, 5000), 2),
            "method": random.choice(["UPI", "Credit Card", "Debit Card", "Net Banking"])
        },
        "timestamp": str(datetime.now())
    }

    transactions.append(transaction)

transactions[:2]

[{'transaction_id': 1,
  'customer': {'customer_id': 94, 'name': 'Allison Castro'},
  'payment': {'amount': 2023.04, 'method': 'Debit Card'},
  'timestamp': '2026-07-27 07:46:49.457837'},
 {'transaction_id': 2,
  'customer': {'customer_id': 2, 'name': 'Richard Flores'},
  'payment': {'amount': 4990.59, 'method': 'Net Banking'},
  'timestamp': '2026-07-27 07:46:49.458025'}]

In [29]:
with open("transactions.json", "w") as file:
    json.dump(transactions, file, indent=4)

print("transactions.json created successfully.")

transactions.json created successfully.

In [30]:
with open("transactions.json", "r") as file:
    print(file.read()[:500])

[
    {
        "transaction_id": 1,
        "customer": {
            "customer_id": 94,
            "name": "Allison Castro"
        },
        "payment": {
            "amount": 2023.04,
            "method": "Debit Card"
        },
        "timestamp": "2026-07-27 07:46:49.457837"
    },
    {
        "transaction_id": 2,
        "customer": {
            "customer_id": 2,
            "name": "Richard Flores"
        },
        "payment": {
            "amount": 4990.59,
            "method"

In [36]:
transactions[0]["payment_details"] = transactions[0].pop("payment")

In [37]:
if "payment" not in transactions[0]:
    print("⚠️ Schema Drift Detected!")
    print("'payment' field has changed to 'payment_details'.")

⚠️ Schema Drift Detected!
'payment' field has changed to 'payment_details'.

In [38]:
config = """
HOST=localhost
PORT=5432
DATABASE=customer_db
USERNAME=admin
PASSWORD=
TIMEOUT=abc
"""

with open("config.txt", "w") as file:
    file.write(config)

print("config.txt created successfully.")

config.txt created successfully.

In [39]:
with open("config.txt", "r") as file:
    config_lines = file.readlines()

print("Configuration Validation:")

for line in config_lines:
    if "=" in line:
        key, value = line.strip().split("=", 1)

        if value == "":
            print(f"Missing value for {key}")

        if key == "TIMEOUT" and not value.isdigit():
            print("TIMEOUT should be numeric")

Configuration Validation:
Missing value for PASSWORD
TIMEOUT should be numeric

In [40]:
conn = sqlite3.connect("customer.db")

df_dirty.to_sql(
    "customers",
    conn,
    if_exists="replace",
    index=False
)

print("Customer data stored successfully!")

Customer data stored successfully!

In [41]:
query = pd.read_sql("SELECT * FROM customers LIMIT 5", conn)

query

,customer_id,name,email,phone,city,state,country,age,registration_date
0,1.0,Robin Hall,christopher15@example.net,712.281.6976x983,Cunninghamfort,Arkansas,Honduras,40,2026-05-21
1,2.0,Raymond Harrington,kevinwilson@example.com,468-792-9134,Ramseyshire,Montana,Guernsey,45,2026-01-10
2,3.0,Terry Mcbride,kristy37@example.net,001-847-782-6754x5413,Robertville,Vermont,Rwanda,47,2025-01-24
3,4.0,Marcus Hubbard,matthewblack@example.org,+1-575-450-6676x0852,Smithberg,Michigan,Lao People's Democratic Republic,40,2025-11-07
4,5.0,Frederick Graham,brandy52@example.com,209-843-8804,Calhounfort,Michigan,North Macedonia,37,2025-08-17

In [42]:
logging.basicConfig(
    filename="validation.log",
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    force=True
)

logging.info("Customer dataset generated.")
logging.warning(f"Missing Customer IDs: {missing_id.shape[0]}")
logging.warning(f"Missing Emails: {missing_email.shape[0]}")
logging.warning(f"Invalid Emails: {invalid_email.shape[0]}")
logging.warning(f"Invalid Phone Numbers: {invalid_phone.shape[0]}")
logging.warning(f"Duplicate Records: {duplicates.shape[0]}")
logging.info("Data validation completed.")

print("validation.log created successfully!")

validation.log created successfully!

In [43]:
with open("validation.log", "r") as file:
    print(file.read())

2026-07-27 07:52:48,922 - INFO - Customer dataset generated.
2026-07-27 07:52:48,924 - WARNING - Missing Customer IDs: 1
2026-07-27 07:52:48,925 - WARNING - Missing Emails: 1
2026-07-27 07:52:48,925 - WARNING - Invalid Emails: 2
2026-07-27 07:52:48,925 - WARNING - Invalid Phone Numbers: 1
2026-07-27 07:52:48,925 - WARNING - Duplicate Records: 1
2026-07-27 07:52:48,925 - INFO - Data validation completed.

In [44]:
conn.close()